# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-20 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travel_plans', '0002_trips'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
