# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-20 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_plans', '0006_trips2_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips2',
            old_name='created_by',
            new_name='createdby',
        ),
    ]
