# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-20 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_plans', '0008_auto_20171020_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips2',
            name='user_created',
        ),
    ]
