# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-16 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_and_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dojos',
            old_name='stat',
            new_name='state',
        ),
    ]
